name: .NET

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
    - run: dotnet test --no-build --verbosity normal
    - name: Codedov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: "Toxicman_DESKTOP-R0MP7SM 2021-09-13 19_33_50.coveragexml"
